# Generated by Django 2.2.10 on 2022-01-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surveys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название товара')),
                ('date_start', models.DateField(verbose_name='Начало опроса')),
                ('date_end', models.DateField(verbose_name='Конец опроса')),
                ('description', models.CharField(db_index=True, max_length=200, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Опросы',
                'verbose_name_plural': 'Опросы',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serveys', models.ManyToManyField(null=True, to='api.Surveys')),
            ],
            options={
                'verbose_name': 'Пользователи',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(db_index=True, max_length=1024, verbose_name='Вопрос')),
                ('question_type', models.CharField(choices=[('Text', 'Ответ текстом'), ('One_answer', 'Выбор одного ответа'), ('Many_answers', 'Выбор нескольких ответов')], default='Text', max_length=13, verbose_name='Тип вопроса')),
                ('survey', models.ManyToManyField(null=True, to='api.Surveys', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Вопросы',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
