# Generated by Django 2.2.10 on 2022-01-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220111_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serveys', models.ManyToManyField(null=True, to='api.Surveys')),
            ],
            options={
                'verbose_name': 'Создатель опросов',
                'verbose_name_plural': 'Создатель опросов',
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serveys', models.ManyToManyField(null=True, to='api.Surveys')),
            ],
            options={
                'verbose_name': 'Гости',
                'verbose_name_plural': 'Гости',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
