# Generated by Django 2.2.10 on 2022-01-11 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220111_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='serveys',
        ),
        migrations.AddField(
            model_name='guest',
            name='serveys',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Surveys'),
        ),
    ]
