# Generated by Django 2.2.10 on 2022-01-11 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220111_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('answer', models.CharField(max_length=1024, verbose_name='Ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answer', to='api.Questions', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответы пользователей',
                'verbose_name_plural': 'Ответы пользователей',
            },
        ),
    ]
