# Generated by Django 2.2.10 on 2022-01-11 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_answers',
            name='surveys',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_answer', to='api.Surveys', verbose_name='Опрос'),
        ),
    ]
