# Generated by Django 2.2.10 on 2022-01-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_answers_surveys'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='answers',
            field=models.TextField(max_length=1024, null=True),
        ),
    ]
